apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "awsProton"
  description: "example using aws proton"
  annotations:
    github.com/project-slug: ybai5github/backstage-aws-proton2
    backstage.io/techdocs-ref: dir:.
    aws.amazon.com/aws-proton-service: arn:aws:proton:us-east-1:947751419169:service/awsProton
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
